# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160428_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='by',
            field=models.CharField(default=b'by', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(default=b'type', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='site_host',
            field=models.CharField(default=b'host', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.CharField(default=b'url', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default=b'title', max_length=100),
        ),
    ]
