# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20160525_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='score_angry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score_happy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score_lol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score_sad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='score_wow',
            field=models.IntegerField(default=0),
        ),
    ]
