# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160503_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='by',
            field=models.CharField(default='by', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(default='type', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='site_host',
            field=models.CharField(default='host', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='title', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='url', max_length=200),
        ),
    ]
