# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160526_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_difference',
            field=models.IntegerField(default=0),
        ),
    ]
