# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_post_time_difference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='site_host',
        ),
    ]
