# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 11:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20160529_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(max_length=200, validators=[django.core.validators.URLValidator]),
        ),
    ]
