# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160530_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.CharField(default='url', max_length=200),
        ),
    ]
