# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-21 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160721_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='owner',
            field=models.CharField(max_length=100),
        ),
    ]
