# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-27 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_post_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(default=0),
        ),
    ]
