# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20160727_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.TextField(default=''),
        ),
    ]
