# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20160730_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='emotion',
            field=models.IntegerField(default=0),
        ),
    ]
