# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_voter_emotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='emotion',
            new_name='emotion_num',
        ),
    ]
