# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-13 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20160813_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='emotion_num',
            new_name='emotion',
        ),
    ]
