# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-17 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_post_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='render_story',
            field=models.BooleanField(default=True),
        ),
    ]
