# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_post_render_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sa_sh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sa_ss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='sa_sw',
            field=models.IntegerField(default=0),
        ),
    ]
